name: scp files on release
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@master
    - name: setup node
      uses: actions/setup-node@v2
      with: 
        node-version: 16
    - run: npm ci
    - run: npm build
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build/"
        target: ${{ secrets.SSH_PATH }}