name: scp files on release
on: [release]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@master
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build/"
        target: ${{ secrets.SSH_PATH }}
