name: scp files on release
on: [push, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@master
    - name: setup node
      uses: actions/setup-node@v2
      with: 
        node-version: 16
    - run: npm ci
    - run: npm run build
    - run: ls -al
    - run: ${{ secrets.SCP_COMMAND }}